### ISSUE TITLE
It doesn't work with the examples

### ISSUE THREAD

**Issue by cag137** [nguyenngochuy91/Ancestral-Blocks-Reconstruction#5]
Dear ROAGUE Team (or whom it may concern):

I'm very excited to use ROAGUE to analyze my data but I haven't been able to run the program.

Quite probably I'm doing something wrong, but I'm trying to run ROAGUE with both the provided examples (E. coli and B. subtilis) as described in the README (and after having installed all the required programs) and I'm getting the same issues.

**1.** Several times in a same run I got:

Building a new DB, current time: 09/24/2019 17:23:36
New DB name:   /opt/tacc_mounts/home1/user/Ancestral-Blocks-Reconstruction/result/db/NC_004917.ffc
New DB title:  result/./db/NC_004917.ffc
Sequence type: Protein
**This was not a protein sequence
a record was omitted**

**And then...**

 CLUSTAL 2.1 Multiple Sequence Alignments

ERROR: Cannot open input file. No alignment!

I'd just like to make sure the program is supposed to run as it currently is or whether you're carrying out some modifications.

Thank you very much!

**Comment by nguyenngochuy91** [comment]
Hi Cag,
Thank you so much for your interest in my pipeline. I believe the problem was in the version of blast. Can you please tell me the blast version you use? (you can use `which blast` in command line or `conda list` to have a list of all package installed by conda). My version is blast 2.6.0. 
The first issue comes from running script formatdb, basically it can't build a db using the sequence file. If you can get the version of blast, we can proceed from there. The second issue is the result of not being able to run blast, therefore, can't do the alignment. 
Again, thank you very much for your enthusiast in our program. I am sorry for this to happen, let me know if it is not clear. 
Huy

**Comment by cag137** [comment]
Huy,

Thank you so much for replying! I think your pipeline can provide promising insight on my data (so hope I can make it work soon).

My Blast version is 2.9.0.

I just run a blastp using a custom db with no problem. So, at least by itself, this version works well in my machine.

**Comment by cag137** [comment]
Hello again!

Sorry to keep bugging you with this. Apparently, I resolved the issue with Blast. I think it had to do with the environment settings and the loaded modules in the cluster I am working in. However, although one step forward, I'm having a problem running ETE because it cannot connect XServer. Reading about this issue, it seems to be related to the configuration (and the absence of X server) in my machine and has nothing to do with the pipeline. 

I will try to solve this and let you know how it goes. 

Again, Thank you!

**Comment by nguyenngochuy91** [comment]
Hi, thank you for letting me know. I hope everything work now. Please don't hesitate if you run into any problem running my pipeline. Wish you the best.
